import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import {
  onairGet,
  resolveCredentials,
  requireCompanyId,
  handleToolError,
} from "../api-client.js";
import { apiKeyParam, companyIdParam, guidParam } from "../schemas.js";
import { CHARACTER_LIMIT } from "../constants.js";

export function registerMissionTools(server: McpServer): void {
  server.registerTool(
    "onair_get_company_jobs",
    {
      title: "Get Company Jobs",
      description: `List pending or completed jobs (missions) for your company.

Set completed=true to get completed jobs instead of pending ones. Each job includes mission type,
departure/destination airports, cargo type/weight, pay amount, and expiration.`,
      inputSchema: {
        completed: z.boolean().default(false).describe("If true, return completed jobs instead of pending."),
        api_key: apiKeyParam,
        company_id: companyIdParam,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async (params) => {
      try {
        const creds = resolveCredentials(params);
        const cid = requireCompanyId(creds);
        const status = params.completed ? "completed" : "pending";
        const jobs = await onairGet<unknown[]>(`company/${cid}/jobs/${status}`, creds.apiKey);

        const text = JSON.stringify(jobs, null, 2);
        if (text.length > CHARACTER_LIMIT) {
          return {
            content: [{
              type: "text" as const,
              text: `${jobs.length} ${status} jobs. Showing first 15:\n${JSON.stringify(jobs.slice(0, 15), null, 2)}`,
            }],
          };
        }
        return {
          content: [{
            type: "text" as const,
            text: jobs.length ? text : `No ${status} jobs found.`,
          }],
        };
      } catch (error) {
        return { content: [{ type: "text" as const, text: handleToolError(error) }], isError: true };
      }
    }
  );

  server.registerTool(
    "onair_get_fbo_jobs",
    {
      title: "Get FBO Jobs",
      description: `List pending jobs generated by a specific FBO (logistic center missions).`,
      inputSchema: {
        fbo_id: guidParam("FBO"),
        api_key: apiKeyParam,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async (params) => {
      try {
        const creds = resolveCredentials(params);
        const jobs = await onairGet<unknown[]>(`fbo/${params.fbo_id}/jobs`, creds.apiKey);
        return {
          content: [{
            type: "text" as const,
            text: jobs.length ? JSON.stringify(jobs, null, 2) : "No pending jobs for this FBO.",
          }],
        };
      } catch (error) {
        return { content: [{ type: "text" as const, text: handleToolError(error) }], isError: true };
      }
    }
  );

  server.registerTool(
    "onair_get_company_work_orders",
    {
      title: "Get Company Work Orders",
      description: `List current maintenance work orders across your fleet.`,
      inputSchema: {
        api_key: apiKeyParam,
        company_id: companyIdParam,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async (params) => {
      try {
        const creds = resolveCredentials(params);
        const cid = requireCompanyId(creds);
        const orders = await onairGet<unknown[]>(`company/${cid}/workorders`, creds.apiKey);
        return {
          content: [{
            type: "text" as const,
            text: orders.length ? JSON.stringify(orders, null, 2) : "No active work orders.",
          }],
        };
      } catch (error) {
        return { content: [{ type: "text" as const, text: handleToolError(error) }], isError: true };
      }
    }
  );

  server.registerTool(
    "onair_get_aircraft_work_orders",
    {
      title: "Get Aircraft Work Orders",
      description: `List maintenance work orders for a specific aircraft.`,
      inputSchema: {
        aircraft_id: guidParam("aircraft"),
        api_key: apiKeyParam,
        company_id: companyIdParam,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async (params) => {
      try {
        const creds = resolveCredentials(params);
        const cid = requireCompanyId(creds);
        const orders = await onairGet<unknown[]>(
          `company/${cid}/aircraft/${params.aircraft_id}/workorders`,
          creds.apiKey
        );
        return {
          content: [{
            type: "text" as const,
            text: orders.length ? JSON.stringify(orders, null, 2) : "No active work orders for this aircraft.",
          }],
        };
      } catch (error) {
        return { content: [{ type: "text" as const, text: handleToolError(error) }], isError: true };
      }
    }
  );
}
